version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 99
    reviewers:
      - zack
    assignees:
      - zack
    labels:
      - dependencies
    commit-message:
      prefix: fix(deps)
      prefix-development: chore
      include: scope
    ignore:
      - dependency-name: webpack
        versions:
          - 4.46.0
